package io.loop.test.SELENIUM.Java.JavaJava.Exceptions;

public class ExceptionsDemo {
    int a = 4;
    // 3 lines
    // try catch





    public static void main(String[] args) {
        int b = 7;
        int c = 0;
        try
        {
            int k=b/c;

            System.out.println(k);

        }
        catch(Exception e)

        {
            System.out.println("I catch the error");
        }
    }
}
